name: Deploy Static HTML to Pages

on:
  push:
    branches: ["main"] # Triggers on push to the main branch
  workflow_dispatch:   # Allows you to trigger the workflow manually

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Point this to the folder containing your index.html ('.' means root)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
